export const projectsData = [
  {
    id: "project-1",
    title: "E-Commerce Platform",
    description: "A full-featured online shopping platform with cart and payment integration",
    image: "/placeholder.svg?height=600&width=800",
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Stripe", "MongoDB"],
    github: "https://github.com",
    demo: "https://example.com",
    type: "Web Application",
    duration: "4 months",
    role: "Full Stack Developer",
    year: 2023,
    features: [
      "User authentication and profiles",
      "Product catalog with search and filtering",
      "Shopping cart and checkout process",
      "Payment processing with Stripe",
      "Order history and tracking",
    ],
    longDescription:
      "This e-commerce platform provides a seamless shopping experience with a focus on performance and user experience. It includes features like product search, filtering, user accounts, shopping cart, and secure checkout with Stripe integration.",
  },
  {
    id: "project-2",
    title: "Task Management App",
    description: "A collaborative task management application with real-time updates",
    image: "/placeholder.svg?height=600&width=800",
    technologies: ["React", "Firebase", "Tailwind CSS", "Redux"],
    github: "https://github.com",
    demo: "https://example.com",
    type: "Web Application",
    duration: "3 months",
    role: "Frontend Developer",
    year: 2023,
    features: [
      "Task creation and assignment",
      "Project organization and categorization",
      "Real-time collaboration",
      "Deadline tracking and notifications",
      "Progress reporting and analytics",
    ],
  },
  {
    id: "project-3",
    title: "Fitness Tracking Mobile App",
    description: "A mobile application for tracking workouts and nutrition",
    image: "/placeholder.svg?height=600&width=800",
    technologies: ["React Native", "TypeScript", "Firebase", "Redux"],
    github: "https://github.com",
    demo: "https://example.com",
    type: "Mobile Application",
    duration: "5 months",
    role: "Mobile Developer",
    year: 2022,
    features: [
      "Workout planning and tracking",
      "Nutrition logging and analysis",
      "Progress visualization with charts",
      "Goal setting and achievement tracking",
      "Social sharing and community features",
    ],
  },
  {
    id: "project-4",
    title: "AI-Powered Content Generator",
    description: "A tool that uses AI to generate various types of content",
    image: "/placeholder.svg?height=600&width=800",
    technologies: ["Python", "TensorFlow", "React", "FastAPI"],
    github: "https://github.com",
    demo: "https://example.com",
    type: "Web Application",
    duration: "6 months",
    role: "ML Engineer & Frontend Developer",
    year: 2022,
  },
  {
    id: "project-5",
    title: "Smart Home Dashboard",
    description: "A dashboard for monitoring and controlling smart home devices",
    image: "/placeholder.svg?height=600&width=800",
    technologies: ["React", "Node.js", "MQTT", "Chart.js"],
    github: "https://github.com",
    demo: "https://example.com",
    type: "IoT Application",
    duration: "4 months",
    role: "Full Stack Developer",
    year: 2021,
  },
  {
    id: "project-6",
    title: "Educational Platform",
    description: "An online learning platform with courses, quizzes, and progress tracking",
    image: "/placeholder.svg?height=600&width=800",
    technologies: ["Next.js", "MongoDB", "Express", "Socket.io"],
    github: "https://github.com",
    demo: "https://example.com",
    type: "Web Application",
    duration: "7 months",
    role: "Full Stack Developer",
    year: 2021,
  },
]

export const testimonialsData = [
  {
    name: "Alex Johnson",
    role: "Senior Developer",
    company: "TechCorp",
    avatar: "/placeholder.svg?height=40&width=40",
    quote:
      "One of the most talented developers I've worked with. Their problem-solving skills and attention to detail are exceptional. They consistently delivered high-quality code and was always willing to help team members.",
  },
  {
    name: "Sarah Williams",
    role: "Project Manager",
    company: "InnovateSoft",
    avatar: "/placeholder.svg?height=40&width=40",
    quote:
      "An outstanding team player with excellent technical skills. They took ownership of complex features and delivered them ahead of schedule. Their communication skills made collaboration seamless.",
  },
  {
    name: "Michael Chen",
    role: "CTO",
    company: "StartupX",
    avatar: "/placeholder.svg?height=40&width=40",
    quote:
      "Rarely do you find someone who combines technical excellence with such strong communication skills. They quickly became an integral part of our team, solving problems we'd been stuck on for weeks.",
  },
  {
    name: "Emily Rodriguez",
    role: "UX Designer",
    company: "DesignHub",
    avatar: "/placeholder.svg?height=40&width=40",
    quote:
      "Working with them was a pleasure. They have a great eye for detail and always considered the user experience in their implementations. Their ability to translate designs into functioning code is impressive.",
  },
  {
    name: "David Kim",
    role: "Product Owner",
    company: "SoftSolutions",
    avatar: "/placeholder.svg?height=40&width=40",
    quote:
      "They have a rare combination of technical expertise and business understanding. They not only built what we asked for but often suggested improvements that made the product better.",
  },
  {
    name: "Lisa Patel",
    role: "Frontend Lead",
    company: "WebWorks",
    avatar: "/placeholder.svg?height=40&width=40",
    quote:
      "Their code is clean, well-documented, and maintainable. They stay up-to-date with the latest technologies and best practices, bringing valuable insights to every project they work on.",
  },
]
